server:
  port:8080
#  servlet:
#    context-path: /suburb-service


spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name:
    username:
    password:

  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: create-drop

    properties.hibernate.enable_lazy_load_no_tans: true
