logging.level.org.springframework.web: INFO
logging.level.org.hibernate: ERROR
logging.level.sql: ERROR
logging.level.root: INFO

server:
  port:8080

spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name:
    username:
    password:

  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: create-drop

    properties.hibernate.enable_lazy_load_no_tans: true

suburb.service.app:
  username: admin
#  password: adminPassword
  password: $2y$10$9BqFgYOBOn6BA/yhzlX8d.r/B/exyQpCL1qeooXJ4XywbIXoX1GHq
